### ISSUE TITLE
build process failing on linkchecker

### ISSUE THREAD

**Issue by csantanapr** [cloud-native-toolkit/developer-guide#471]
When opening a PR the PR is failing with link breaks on the `404` page

```
URL        `/reference/cli/'
Name       `Command Line Tool'
Parent URL file:///github/workspace/public/404.html, line 56, col 13901
Real URL   file:///reference/cli/
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/reference/cli/'>
```

Here is an instance https://github.com/cloud-native-toolkit/developer-guide/pull/470/checks?check_run_id=2822722794

cc @bwoolf1

**Comment by binnes** [comment]
This is due to a change to the mkdocs-materials container, which we use as the base image for the build action.  They changed the links in the 404.html file from relative to absolute, which breaks the linkcheckerrc, as the file links now start with /, so the root of the filesystem

Fix:
Modified the linkchecker config to set the site root : in PR #470 
Updated the Dockerfiles to use a specified tag, so we can decide when to take new releases : in PR #472
